version: '3.9'
services:
  api:
    build:
      context: .
    image: gultruekanekisss/exam_bot
    ports:
      - 80:80
    volumes:
      - ./docker_config.py:/code/default_config.py
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: tg_bot
      POSTGRES_PASSWORD: tg_bot_password
      POSTGRES_DB: tg_bot
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
